function renderHome(){
 let cards='';for(let n=1;n<=5;n++){const s=getState(n);const answered=s?Object.keys(s.responses||{}).length:0;const finished=s?.finished;cards+=`<section class="exam-card"><h3>Practice Exam ${n}</h3><p>90 questions · 5 interactive PBQs · 85 multiple choice · 90 minutes</p><div class="progress-track"><div class="progress-bar" style="width:${finished?100:Math.round(answered/90*100)}%"></div></div><p class="small">${finished?'Completed':answered?answered+' questions answered':'Not started'}</p><div class="btnrow"><button class="btn btn-primary start" data-exam="${n}">${finished?'Retake':s?'Resume':'Start exam'}</button>${s?`<button class="btn btn-secondary reset" data-exam="${n}">Reset</button>`:''}${finished?`<button class="btn btn-secondary results" data-exam="${n}">Results</button>`:''}</div></section>`}
 document.getElementById('app').innerHTML=shellTop()+`<main><h1>CompTIA Security+ SY0-701 Practice Simulator</h1><p class="lead">Five full 90-question practice exams built from your existing study pack. PBQs are converted into touch-friendly dropdown, drag-and-drop, sequence, calculation, and diagram interactions.</p><section class="mode-box"><strong>Start mode</strong><label><input type="radio" name="mode" value="exam" checked> Timed exam — answers stay hidden until you finish.</label><label><input type="radio" name="mode" value="study"> Study mode — use “Check answer” while working.</label></section><div class="home-grid">${cards}</div><div class="install-note"><strong>Tablet ready:</strong> large touch targets, S Pen/mouse support, landscape layout, offline question bank, and automatic local progress saving. This is original practice material, not actual CompTIA exam content.</div></main>`;
 document.querySelectorAll('.start').forEach(b=>b.addEventListener('click',()=>startExam(+b.dataset.exam)));
 document.querySelectorAll('.reset').forEach(b=>b.addEventListener('click',()=>{if(confirm('Reset this exam and erase its saved answers?')){delete db['exam'+b.dataset.exam];saveDB();render()}}));
 document.querySelectorAll('.results').forEach(b=>b.addEventListener('click',()=>{view={screen:'results',exam:+b.dataset.exam,index:0,feedback:false,selectedToken:null};render()}));
}
function startExam(n){const mode=document.querySelector('input[name=mode]:checked')?.value||'exam';let s=getState(n);if(!s||s.finished){s=defaultState(n,mode);db['exam'+n]=s;saveDB()}view={screen:'exam',exam:n,index:s.index||0,feedback:false,selectedToken:null};render()}
function updateTimer(){const s=currentState();if(!s||s.finished)return;const elapsed=Math.floor((Date.now()-s.startedAt)/1000);const rem=Math.max(0,5400-elapsed);s.remaining=rem;const el=document.getElementById('timer');if(el)el.textContent=formatTime(rem);if(rem<=0)finishExam(true);}
function renderExam(){const s=currentState();const data=examData(view.exam);view.index=Math.max(0,Math.min(89,view.index));s.index=view.index;saveDB();const q=data.questions[view.index];const answered=data.questions.filter(x=>isAnswered(x,s.responses[x.number])).length;const flagged=Object.keys(s.flagged||{}).filter(k=>s.flagged[k]).length;let palette='';data.questions.forEach((x,i)=>{palette+=`<button class="qnum ${isAnswered(x,s.responses[x.number])?'answered':''} ${s.flagged[x.number]?'flagged':''} ${i===view.index?'current':''}" data-i="${i}">${x.number}</button>`});
 const top=`<div class="topmeta"><span class="pill">Exam ${view.exam}</span><span class="pill" id="timer">${formatTime(s.remaining)}</span><button class="btn btn-ghost homebtn">Exit</button></div>`;
 document.getElementById('app').innerHTML=shellTop(top)+`<main><div class="progress-track"><div class="progress-bar" style="width:${Math.round(answered/90*100)}%"></div></div><div class="exam-shell"><section class="question-card">${renderQuestion(q,s)}</section><aside class="sidebar"><strong>Question navigator</strong><div class="statline"><span>Answered</span><b>${answered} / 90</b></div><div class="statline"><span>Flagged</span><b>${flagged}</b></div><div class="palette">${palette}</div><div class="btnrow" style="margin-top:14px"><button class="btn btn-danger finishbtn">Finish exam</button></div></aside></div></main>`;
 bindExamHandlers(q,s);timerHandle=setInterval(updateTimer,1000);updateTimer();}
function renderQuestion(q,s){const flag=s.flagged[q.number];let body=q.type==='mcq'?renderMCQ(q,s):renderPBQ(q,s);let check=s.mode==='study'?`<button class="btn btn-secondary checkbtn">Check answer</button>`:'';let feedback='';if(s.mode==='study'&&s.checked[q.number])feedback=renderFeedback(q,s.responses[q.number]);return `<div class="qhead"><div><span class="qtag">${q.type==='pbq'?'PBQ · Domain '+q.domain:'Question '+q.number+' · Domain '+q.domain}</span><h2 style="margin-top:10px">${q.type==='pbq'?escapeHTML(q.title):'Question '+q.number}</h2></div><button class="btn btn-secondary flagbtn ${flag?'active':''}">${flag?'★ Flagged':'☆ Flag for review'}</button></div>${body}${feedback}<div class="navbar"><button class="btn btn-secondary prevbtn" ${view.index===0?'disabled':''}>← Previous</button><div class="btnrow">${check}<button class="btn btn-primary nextbtn">${view.index===89?'Finish':'Next →'}</button></div></div>`}
function renderMCQ(q,s){const r=s.responses[q.number];let opts='';for(const [k,v] of Object.entries(q.options))opts+=`<label class="option"><input type="radio" name="mcq" value="${k}" ${r===k?'checked':''}><span><b>${k}.</b> ${escapeHTML(v)}</span></label>`;return `<div class="stem">${escapeHTML(q.stem)}</div>${opts}`}
