function renderPBQ(q,s){const r=s.responses[q.number]||{};const intro=`<div class="pbq-instruction"><strong>${escapeHTML(q.instruction)}</strong></div>`;if(q.interaction==='dropdown_match')return intro+renderDropdown(q,r);if(q.interaction==='drag_match')return intro+renderDragMatch(q,r);if(q.interaction==='diagram_match')return intro+renderDiagram(q,r);if(q.interaction==='sequence_plus_match')return intro+renderSequence(q,r);if(q.interaction==='risk_calc')return intro+renderRisk(q,r);return intro+renderDropdown(q,r)}
function renderDropdown(q,r){const pool=pbqPool(q.domain,q.answers);return q.items.map((item,i)=>`<div class="pbq-row"><div><b>${i+1}.</b> ${escapeHTML(item)}</div><select class="pbq-select" data-i="${i}"><option value="">Choose an answer…</option>${pool.map(v=>`<option value="${escapeHTML(v)}" ${r[i]===v?'selected':''}>${escapeHTML(v)}</option>`).join('')}</select></div>`).join('')}
function availableTokens(q,r){return pbqPool(q.domain,q.answers).map(v=>({v,used:Object.values(r||{}).includes(v)}))}
function renderDragMatch(q,r){const tokens=availableTokens(q,r);return `<p class="small">Drag an answer to a target. On touch screens you can also tap an answer, then tap the target.</p><div class="answer-bank">${tokens.map(t=>`<button type="button" class="drag-token ${t.used?'used':''}" data-value="${escapeHTML(t.v)}">${escapeHTML(t.v)}</button>`).join('')}</div><div class="match-grid">${q.items.map((it,i)=>`<div class="match-card"><div><b>${i+1}.</b> ${escapeHTML(it)}</div><div class="drop-zone ${r[i]?'filled':''}" data-i="${i}">${r[i]?escapeHTML(r[i]):'Drop answer here'}</div></div>`).join('')}</div>`}
function renderDiagram(q,r){const tokens=availableTokens(q,r);return `<p class="small">Architecture workspace — place each control/concept onto the requirement node.</p><div class="answer-bank">${tokens.map(t=>`<button type="button" class="drag-token ${t.used?'used':''}" data-value="${escapeHTML(t.v)}">${escapeHTML(t.v)}</button>`).join('')}</div><div class="diagram"><div class="diagram-center">🔐 Security Architecture</div><div class="diagram-grid">${q.items.map((it,i)=>`<div class="diagram-node"><div class="node-title">Node ${i+1}</div><div class="small" style="margin-bottom:8px">${escapeHTML(it)}</div><div class="drop-zone ${r[i]?'filled':''}" data-i="${i}">${r[i]?escapeHTML(r[i]):'Place control'}</div></div>`).join('')}</div></div>`}
function renderSequence(q,r){const phases=['Analysis','Recovery','Containment','Detection','Eradication'];const seq=r.sequence||[];const used=new Set(seq);const pool=pbqPool(q.domain,q.answers.slice(1));return `<div><strong>1. ${escapeHTML(q.items[0])}</strong><p class="small">Drag/tap the phases into positions 1–5.</p><div class="answer-bank">${phases.map(v=>`<button type="button" class="drag-token seq-token ${used.has(v)?'used':''}" data-value="${v}">${v}</button>`).join('')}</div><div class="sequence-slots">${[0,1,2,3,4].map(i=>`<div class="seq-slot ${seq[i]?'filled':''}" data-seq="${i}"><b>Position ${i+1}</b><span>${seq[i]||'Drop phase'}</span></div>`).join('')}</div></div>${q.items.slice(1).map((item,j)=>`<div class="pbq-row"><div><b>${j+2}.</b> ${escapeHTML(item)}</div><select class="seq-select" data-i="${j+1}"><option value="">Choose…</option>${pool.map(v=>`<option value="${escapeHTML(v)}" ${r.match?.[j+1]===v?'selected':''}>${escapeHTML(v)}</option>`).join('')}</select></div>`).join('')}`}
function renderRisk(q,r){const pool=pbqPool(q.domain,q.answers.slice(2));return q.items.map((item,i)=>{if(i<2)return `<div class="pbq-row"><div><b>${i+1}.</b> ${escapeHTML(item)}</div><input class="risk-input" data-i="${i}" inputmode="numeric" placeholder="Enter amount" value="${escapeHTML(r[i]||'')}"></div>`;return `<div class="pbq-row"><div><b>${i+1}.</b> ${escapeHTML(item)}</div><select class="risk-select" data-i="${i}"><option value="">Choose…</option>${pool.map(v=>`<option value="${escapeHTML(v)}" ${r[i]===v?'selected':''}>${escapeHTML(v)}</option>`).join('')}</select></div>`}).join('')}
function renderFeedback(q,r){const sc=scoreQuestion(q,r),ok=sc.earned===sc.max;if(q.type==='mcq'){const selected=r&&q.options[r]?`${r}. ${q.options[r]}`:'No answer';const exp=q.explanation||{};const optionRows=Object.entries(q.options).filter(([k])=>k!==q.answer).map(([k,v])=>`<li><strong>${k}. ${escapeHTML(v)}</strong><br>${escapeHTML(exp.options?.[k]||'This option does not meet the specific facts and constraints in the question.')}</li>`).join('');return `<div class="feedback ${ok?'good':'bad'}"><strong>${ok?'Correct':'Review this one'} — ${sc.earned}/${sc.max} point</strong><div class="answer-section"><h3>Your answer</h3><p>${escapeHTML(selected)}</p><h3>Correct answer</h3><p><strong>${q.answer}. ${escapeHTML(q.options[q.answer])}</strong></p><h3>Why it is correct</h3><p>${escapeHTML(exp.correct||q.rationale||'')}</p><h3>Why the other answers are incorrect</h3><ul class="option-explanations">${optionRows}</ul></div></div>`}const itemRows=q.items.map((item,i)=>{let actual=q.interaction==='sequence_plus_match'?(i===0?(r?.sequence||[]).join(' -> '):r?.match?.[i]):r?.[i];const itemOk=normalize(actual)===normalize(q.answers[i]);return `<li class="${itemOk?'goodtext':'dangertext'}"><strong>Item ${i+1}: ${escapeHTML(q.answers[i])}</strong><br>${escapeHTML(q.explanation?.items?.[i]||'This response directly matches the stated requirement.')}<br><span class="small">Your response: ${escapeHTML(actual||'No answer')}</span></li>`}).join('');return `<div class="feedback ${ok?'good':'bad'}"><strong>${ok?'Correct':'Review this PBQ'} — ${sc.earned}/${sc.max} points</strong><div class="answer-section"><h3>Expected configuration and reasoning</h3><ol class="option-explanations">${itemRows}</ol></div></div>`}
function bindExamHandlers(q,s){document.querySelector('.homebtn').addEventListener('click',()=>{view.screen='home';render()});document.querySelector('.flagbtn').addEventListener('click',()=>{s.flagged[q.number]=!s.flagged[q.number];saveDB();renderExam()});document.querySelector('.prevbtn').addEventListener('click',()=>{if(view.index>0){view.index--;view.feedback=false;renderExam()}});document.querySelector('.nextbtn').addEventListener('click',()=>{if(view.index===89)finishExam(false);else{view.index++;view.feedback=false;renderExam()}});document.querySelector('.finishbtn').addEventListener('click',()=>finishExam(false));document.querySelectorAll('.qnum').forEach(b=>b.addEventListener('click',()=>{view.index=+b.dataset.i;renderExam()}));document.querySelector('.checkbtn')?.addEventListener('click',()=>{s.checked[q.number]=true;saveDB();renderExam()});
 if(q.type==='mcq')document.querySelectorAll('input[name=mcq]').forEach(el=>el.addEventListener('change',()=>{s.responses[q.number]=el.value;saveDB()}));
 else bindPBQ(q,s);
}
function ensureObj(s,q){if(!s.responses[q.number]||typeof s.responses[q.number]!=='object')s.responses[q.number]={};return s.responses[q.number]}
function bindPBQ(q,s){let r=ensureObj(s,q);document.querySelectorAll('.pbq-select').forEach(el=>el.addEventListener('change',()=>{r[el.dataset.i]=el.value;saveDB()}));document.querySelectorAll('.risk-input').forEach(el=>el.addEventListener('input',()=>{r[el.dataset.i]=el.value;saveDB()}));document.querySelectorAll('.risk-select').forEach(el=>el.addEventListener('change',()=>{r[el.dataset.i]=el.value;saveDB()}));if(q.interaction==='sequence_plus_match'){if(!r.match)r.match={};if(!r.sequence)r.sequence=[];document.querySelectorAll('.seq-select').forEach(el=>el.addEventListener('change',()=>{r.match[el.dataset.i]=el.value;saveDB()}));document.querySelectorAll('.seq-slot').forEach(z=>z.addEventListener('click',()=>{const i=+z.dataset.seq;if(view.selectedToken){r.sequence=r.sequence.filter(x=>x!==view.selectedToken);r.sequence[i]=view.selectedToken;view.selectedToken=null;saveDB();renderExam()}else if(r.sequence[i]){r.sequence.splice(i,1);saveDB();renderExam()}}));}
 bindDragTokens(q,s,r);
}
function bindDragTokens(q,s,r){document.querySelectorAll('.drag-token').forEach(tok=>{tok.addEventListener('click',e=>{if(tok.classList.contains('used'))return;view.selectedToken=tok.dataset.value;document.querySelectorAll('.drag-token').forEach(t=>t.classList.toggle('selected',t===tok))});tok.addEventListener('pointerdown',e=>startPointerDrag(e,tok,q,s,r))});document.querySelectorAll('.drop-zone').forEach(z=>z.addEventListener('click',()=>{const i=+z.dataset.i;if(view.selectedToken){Object.keys(r).forEach(k=>{if(r[k]===view.selectedToken)delete r[k]});r[i]=view.selectedToken;view.selectedToken=null;saveDB();renderExam()}else if(r[i]){delete r[i];saveDB();renderExam()}}));}
function startPointerDrag(e,tok,q,s,r){if(tok.classList.contains('used'))return;const value=tok.dataset.value;const ghost=document.createElement('div');ghost.className='drag-ghost';ghost.textContent=value;document.body.appendChild(ghost);ghost.style.left=e.clientX+'px';ghost.style.top=e.clientY+'px';tok.setPointerCapture?.(e.pointerId);let moved=false;const move=ev=>{moved=true;ghost.style.left=ev.clientX+'px';ghost.style.top=ev.clientY+'px'};const up=ev=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up);ghost.remove();if(!moved)return;const target=document.elementFromPoint(ev.clientX,ev.clientY);const zone=target?.closest('.drop-zone,.seq-slot');if(!zone)return;if(zone.classList.contains('seq-slot')){if(!r.sequence)r.sequence=[];r.sequence=r.sequence.filter(x=>x!==value);r.sequence[+zone.dataset.seq]=value;}else{Object.keys(r).forEach(k=>{if(r[k]===value)delete r[k]});r[+zone.dataset.i]=value;}saveDB();renderExam()};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up,{once:true})}

