let BANK=[];
const DOMAIN_NAMES={1:'General Security Concepts',2:'Threats, Vulnerabilities & Mitigations',3:'Security Architecture',4:'Security Operations',5:'Security Program Management & Oversight'};
const STORAGE='securityplus701-simulator-v2';
let db=loadDB();
let view={screen:'home',exam:null,index:0,feedback:false,selectedToken:null};
let timerHandle=null;
function loadDB(){try{return JSON.parse(localStorage.getItem(STORAGE))||{}}catch(e){return {}}}
function saveDB(){localStorage.setItem(STORAGE,JSON.stringify(db))}
function defaultState(exam,mode='exam'){return {exam,mode,index:0,responses:{},flagged:{},checked:{},startedAt:Date.now(),remaining:5400,finished:false,result:null}}
function getState(exam){return db['exam'+exam]}
function currentState(){return view.exam?getState(view.exam):null}
function escapeHTML(s){return String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
const ACRONYM_NAMES={ABAC:'Attribute-Based Access Control',ALE:'Annualized Loss Expectancy',API:'Application Programming Interface',ARO:'Annualized Rate of Occurrence',BYOD:'Bring Your Own Device',COPE:'Corporate-Owned, Personally Enabled',CRL:'Certificate Revocation List',CSR:'Certificate Signing Request',CVE:'Common Vulnerabilities and Exposures',CVSS:'Common Vulnerability Scoring System',CYOD:'Choose Your Own Device',DKIM:'DomainKeys Identified Mail',DLP:'Data Loss Prevention',DMARC:'Domain-based Message Authentication, Reporting, and Conformance',DNS:'Domain Name System',EAP:'Extensible Authentication Protocol',EDR:'Endpoint Detection and Response',HSM:'Hardware Security Module',HTTP:'Hypertext Transfer Protocol',ICS:'Industrial Control System',IDS:'Intrusion Detection System',IP:'Internet Protocol',IPS:'Intrusion Prevention System',IT:'Information Technology',MDM:'Mobile Device Management',MFA:'Multi-Factor Authentication',MOU:'Memorandum of Understanding',MSA:'Master Service Agreement',MTBF:'Mean Time Between Failures',MTTR:'Mean Time to Repair',NAC:'Network Access Control',NAS:'Network-Attached Storage',NDA:'Non-Disclosure Agreement',NGFW:'Next-Generation Firewall',OCSP:'Online Certificate Status Protocol',OSINT:'Open-Source Intelligence',RADIUS:'Remote Authentication Dial-In User Service',RBAC:'Role-Based Access Control',RPO:'Recovery Point Objective',RTO:'Recovery Time Objective',SAML:'Security Assertion Markup Language',SASE:'Secure Access Service Edge',SCADA:'Supervisory Control and Data Acquisition',SCAP:'Security Content Automation Protocol',SIEM:'Security Information and Event Management',SLA:'Service-Level Agreement',SLE:'Single Loss Expectancy',SMS:'Short Message Service',SNMP:'Simple Network Management Protocol',SOW:'Statement of Work',SPF:'Sender Policy Framework',SQL:'Structured Query Language',SSO:'Single Sign-On',TLS:'Transport Layer Security',TPM:'Trusted Platform Module',UPS:'Uninterruptible Power Supply',VM:'Virtual Machine',VPN:'Virtual Private Network',WAF:'Web Application Firewall',WPA3:'Wi-Fi Protected Access 3',XDR:'Extended Detection and Response'};
const ACRONYM_PATTERN=new RegExp(`\\b(${Object.keys(ACRONYM_NAMES).sort((a,b)=>b.length-a.length).join('|')})\\b(?!\\s*\\()`,'g');
function expandAcronyms(s){return String(s??'').replace(ACRONYM_PATTERN,a=>`${a} (${ACRONYM_NAMES[a]})`)}
function displayLearningText(s){return escapeHTML(expandAcronyms(s))}
function shuffle(a){let x=[...a];for(let i=x.length-1;i>0;i--){let j=(i*7+3)% (i+1);[x[i],x[j]]=[x[j],x[i]]}return x}
function examData(n){return BANK[n-1]}
function qData(n,i){return examData(n).questions[i]}
function formatTime(sec){sec=Math.max(0,Math.floor(sec));return String(Math.floor(sec/60)).padStart(2,'0')+':'+String(sec%60).padStart(2,'0')}
function normalize(s){return String(s??'').toLowerCase().replace(/[$,]/g,'').replace(/[.]/g,'').replace(/\s+/g,' ').trim()}
function isAnswered(q,r){if(!r)return false;if(q.type==='mcq')return !!r;if(q.interaction==='sequence_plus_match')return (r.sequence?.length||0)>0||Object.keys(r.match||{}).length>0;return Object.keys(r||{}).length>0}
function responseFor(q){const s=currentState();return s.responses[q.number]||null}
function pbqPool(domain,currentAnswers){let pool=[];BANK.forEach(e=>e.questions.filter(q=>q.type==='pbq'&&q.domain===domain).forEach(q=>pool.push(...q.answers)));pool=[...new Set(pool)].filter(Boolean);const current=new Set(currentAnswers);const distract=pool.filter(x=>!current.has(x)).slice(0,5);return shuffle([...currentAnswers,...distract])}
function scoreQuestion(q,r){if(q.type==='mcq')return {earned:r===q.answer?1:0,max:1};let earned=0,max=q.answers.length;if(q.interaction==='sequence_plus_match'){const seq=(r?.sequence||[]).join(' -> ');if(normalize(seq)===normalize(q.answers[0]))earned++;for(let i=1;i<q.answers.length;i++)if(normalize(r?.match?.[i])===normalize(q.answers[i]))earned++;}else{for(let i=0;i<q.answers.length;i++)if(normalize(r?.[i])===normalize(q.answers[i]))earned++;}return {earned,max}}
function estimatedScaledScore(percent){return Math.max(100,Math.min(900,Math.round((100+percent*8)/10)*10))}
function readinessFor(score){if(score>=800)return {label:'Strong readiness',className:'goodtext',detail:'Consistently above the 750 reference point; continue targeted review.'};if(score>=750)return {label:'Approaching exam readiness',className:'goodtext',detail:'At or above the 750 reference point; reinforce weaker domains before testing.'};if(score>=650)return {label:'Developing readiness',className:'warntext',detail:'Close enough for focused remediation; prioritize the weakest domains and PBQs.'};return {label:'More preparation recommended',className:'dangertext',detail:'Build fundamentals and retest after focused study.'}}
function attemptHistory(){if(!Array.isArray(db.history))db.history=[];for(let n=1;n<=5;n++){const s=getState(n);if(!s?.finished||!s.result)continue;const id=s.result.attemptId||`legacy-${n}-${s.startedAt||0}`;if(!db.history.some(a=>a.id===id))db.history.push({id,exam:n,completedAt:s.result.completedAt||s.startedAt||Date.now(),percent:s.result.percent,estimatedScore:s.result.estimatedScore||estimatedScaledScore(s.result.percent),domains:s.result.domains,pbqEarn:s.result.pbqEarn,pbqMax:s.result.pbqMax})}saveDB();return db.history}
function domainStatus(percent){if(percent>=80)return {label:'Strong',className:'status-strong'};if(percent>=70)return {label:'Developing',className:'status-developing'};return {label:'Needs attention',className:'status-attention'}}
function render(){clearInterval(timerHandle);if(view.screen==='home')renderHome();else if(view.screen==='exam')renderExam();else if(view.screen==='dashboard')renderDashboard();else renderResults();}
function shellTop(content=''){return `<div class="topbar"><div class="brand">Security+ SY0-701 Simulator</div>${content}</div>`}

